#!/bin/bash

# This script will compile and fire up a proxy server
# This script takes in the first argument as the port number for the server
# This script will fire up the server using the port provided

function usage {
	echo "Usage: ./run <port>"
	echo "<port> is specified as the port number used for the proxy server"
	echo "Port should be ranged from 1100 to 49151"
}

if [ $# != 1 ];then
	usage
	exit 1
fi

port="$1"

if [ $port \< "1100" -o $port \> "49151" ]; then
	echo "Port should be ranged from 1100 to 49151"
	exit 1
fi


mvn compile;
mvn exec:java -Dexec.mainClass="Server.Proxy" -Dexec.args="$port"
